server:
  port: 8060
  session:
    timeout: 300     # session 过期时间(单位秒)，默认至少一分钟，设置低于一分钟会被spring重置为1分钟
spring:
    # DataSource
    datasource:
      # driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost/security_db?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 112358
      driver-class-name: com.mysql.jdbc.Driver
    # Session storage config
    session:
      store-type: REDIS   # 使用 REDIS 统一管理 session

security:
  basic:
    enabled: false  # 关闭基于 HTTP Basic的认证，Spring Security 默认会通过HTTP Basic做认证授权，生成一个user用户和一个随机密码
kwseeker:
  security:
    browser:
      loginPage: /login-demo.html
#      loginType: REDIRECT
      loginType: JSON
      rememberMeSeconds: 60   # 测试token临时定为60秒过期, 服务器的登录超时（即Session, 好像30分钟无动作会退出登录或服务器重启重置为未登录状态）与Token超时（在一段时间内不用手动登录）不同
    imageCode:
      length: 6
      width: 80
#      url: /user/*
